/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as RiderRouteImport } from './routes/rider'
import { Route as CartRouteImport } from './routes/cart'
import { Route as BecomeRiderRouteImport } from './routes/become-rider'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RiderIndexRouteImport } from './routes/rider.index'
import { Route as OrdersIndexRouteImport } from './routes/orders.index'
import { Route as ShopStoreIdRouteImport } from './routes/shop.$storeId'
import { Route as RiderEarningsRouteImport } from './routes/rider.earnings'
import { Route as RiderActiveRouteImport } from './routes/rider.active'
import { Route as OrdersIdRouteImport } from './routes/orders.$id'

const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const RiderRoute = RiderRouteImport.update({
  id: '/rider',
  path: '/rider',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const BecomeRiderRoute = BecomeRiderRouteImport.update({
  id: '/become-rider',
  path: '/become-rider',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RiderIndexRoute = RiderIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => RiderRoute,
} as any)
const OrdersIndexRoute = OrdersIndexRouteImport.update({
  id: '/orders/',
  path: '/orders/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopStoreIdRoute = ShopStoreIdRouteImport.update({
  id: '/$storeId',
  path: '/$storeId',
  getParentRoute: () => ShopRoute,
} as any)
const RiderEarningsRoute = RiderEarningsRouteImport.update({
  id: '/earnings',
  path: '/earnings',
  getParentRoute: () => RiderRoute,
} as any)
const RiderActiveRoute = RiderActiveRouteImport.update({
  id: '/active',
  path: '/active',
  getParentRoute: () => RiderRoute,
} as any)
const OrdersIdRoute = OrdersIdRouteImport.update({
  id: '/orders/$id',
  path: '/orders/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/become-rider': typeof BecomeRiderRoute
  '/cart': typeof CartRoute
  '/rider': typeof RiderRouteWithChildren
  '/shop': typeof ShopRouteWithChildren
  '/orders/$id': typeof OrdersIdRoute
  '/rider/active': typeof RiderActiveRoute
  '/rider/earnings': typeof RiderEarningsRoute
  '/shop/$storeId': typeof ShopStoreIdRoute
  '/orders/': typeof OrdersIndexRoute
  '/rider/': typeof RiderIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/become-rider': typeof BecomeRiderRoute
  '/cart': typeof CartRoute
  '/shop': typeof ShopRouteWithChildren
  '/orders/$id': typeof OrdersIdRoute
  '/rider/active': typeof RiderActiveRoute
  '/rider/earnings': typeof RiderEarningsRoute
  '/shop/$storeId': typeof ShopStoreIdRoute
  '/orders': typeof OrdersIndexRoute
  '/rider': typeof RiderIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/become-rider': typeof BecomeRiderRoute
  '/cart': typeof CartRoute
  '/rider': typeof RiderRouteWithChildren
  '/shop': typeof ShopRouteWithChildren
  '/orders/$id': typeof OrdersIdRoute
  '/rider/active': typeof RiderActiveRoute
  '/rider/earnings': typeof RiderEarningsRoute
  '/shop/$storeId': typeof ShopStoreIdRoute
  '/orders/': typeof OrdersIndexRoute
  '/rider/': typeof RiderIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/become-rider'
    | '/cart'
    | '/rider'
    | '/shop'
    | '/orders/$id'
    | '/rider/active'
    | '/rider/earnings'
    | '/shop/$storeId'
    | '/orders/'
    | '/rider/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/auth'
    | '/become-rider'
    | '/cart'
    | '/shop'
    | '/orders/$id'
    | '/rider/active'
    | '/rider/earnings'
    | '/shop/$storeId'
    | '/orders'
    | '/rider'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/become-rider'
    | '/cart'
    | '/rider'
    | '/shop'
    | '/orders/$id'
    | '/rider/active'
    | '/rider/earnings'
    | '/shop/$storeId'
    | '/orders/'
    | '/rider/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AuthRoute: typeof AuthRoute
  BecomeRiderRoute: typeof BecomeRiderRoute
  CartRoute: typeof CartRoute
  RiderRoute: typeof RiderRouteWithChildren
  ShopRoute: typeof ShopRouteWithChildren
  OrdersIdRoute: typeof OrdersIdRoute
  OrdersIndexRoute: typeof OrdersIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rider': {
      id: '/rider'
      path: '/rider'
      fullPath: '/rider'
      preLoaderRoute: typeof RiderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/become-rider': {
      id: '/become-rider'
      path: '/become-rider'
      fullPath: '/become-rider'
      preLoaderRoute: typeof BecomeRiderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rider/': {
      id: '/rider/'
      path: '/'
      fullPath: '/rider/'
      preLoaderRoute: typeof RiderIndexRouteImport
      parentRoute: typeof RiderRoute
    }
    '/orders/': {
      id: '/orders/'
      path: '/orders'
      fullPath: '/orders/'
      preLoaderRoute: typeof OrdersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop/$storeId': {
      id: '/shop/$storeId'
      path: '/$storeId'
      fullPath: '/shop/$storeId'
      preLoaderRoute: typeof ShopStoreIdRouteImport
      parentRoute: typeof ShopRoute
    }
    '/rider/earnings': {
      id: '/rider/earnings'
      path: '/earnings'
      fullPath: '/rider/earnings'
      preLoaderRoute: typeof RiderEarningsRouteImport
      parentRoute: typeof RiderRoute
    }
    '/rider/active': {
      id: '/rider/active'
      path: '/active'
      fullPath: '/rider/active'
      preLoaderRoute: typeof RiderActiveRouteImport
      parentRoute: typeof RiderRoute
    }
    '/orders/$id': {
      id: '/orders/$id'
      path: '/orders/$id'
      fullPath: '/orders/$id'
      preLoaderRoute: typeof OrdersIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface RiderRouteChildren {
  RiderActiveRoute: typeof RiderActiveRoute
  RiderEarningsRoute: typeof RiderEarningsRoute
  RiderIndexRoute: typeof RiderIndexRoute
}

const RiderRouteChildren: RiderRouteChildren = {
  RiderActiveRoute: RiderActiveRoute,
  RiderEarningsRoute: RiderEarningsRoute,
  RiderIndexRoute: RiderIndexRoute,
}

const RiderRouteWithChildren = RiderRoute._addFileChildren(RiderRouteChildren)

interface ShopRouteChildren {
  ShopStoreIdRoute: typeof ShopStoreIdRoute
}

const ShopRouteChildren: ShopRouteChildren = {
  ShopStoreIdRoute: ShopStoreIdRoute,
}

const ShopRouteWithChildren = ShopRoute._addFileChildren(ShopRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AuthRoute: AuthRoute,
  BecomeRiderRoute: BecomeRiderRoute,
  CartRoute: CartRoute,
  RiderRoute: RiderRouteWithChildren,
  ShopRoute: ShopRouteWithChildren,
  OrdersIdRoute: OrdersIdRoute,
  OrdersIndexRoute: OrdersIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
